# Generated by Django 4.2.23 on 2025-09-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('profile_picture_path', models.CharField(blank=True, default=None, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('album', models.CharField(max_length=2000)),
                ('duration', models.IntegerField()),
                ('file_path', models.CharField(max_length=5000)),
                ('cover_art_path', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('lyrics', models.TextField(blank=True, default=None, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='rhythm_wallet.artist')),
            ],
        ),
    ]
