# Generated by Django 4.2.23 on 2025-09-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bit_depth',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='bit_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='sample_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('cover_art_path', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('genre', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='rhythm_wallet.artist')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='rhythm_wallet.album'),
        ),
    ]
