# Generated by Django 4.2.23 on 2025-09-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm_wallet', '0002_song_bit_depth_song_bit_rate_song_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_art_path',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_picture_path',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_art_path',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_art_mime_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='bit_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sample_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
