# Generated by Django 4.2.23 on 2025-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm_wallet', '0003_remove_album_cover_art_path_remove_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art_mime_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(),
        ),
    ]
