# Generated by Django 4.2.23 on 2025-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm_wallet', '0004_album_cover_art_mime_type_alter_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='rhythm_wallet.song')),
            ],
        ),
    ]
